version: '3.8'
services:
  db:
    image: postgres:13
    container_name: desafioSerUtil
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: desafioSerUtil
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: